### PR TITLE
[FEATURE] adds support for multiple attachments

### PR DESCRIPTION
**Pull request by rommelfreddy**
### Description

This pull request adds the feature that the shop owner can upload multiple attachment files. 
Additionally I added fields to define the filename of the attached file. 
If no custom filename is provided the filename of file will be taken.

### Fixed Issues (if relevant)

1. none

### Manual testing scenarios

1. upload multiple files in the admin
2. check if all files has been attached as expected

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)

### CODE REVIEW

**Comment by TeddyMageplaza** [comment]
Hello @rommelfreddy,

I am Teddy from Mageplaza and thank you so much for your contribution. My team is checking the modifications and will get back to you soon.

Best Regards,
Teddy

**Comment by rommelfreddy** [comment]
Hello @TeddyMageplaza 
is there an update on this PR ? :)

**Comment by TeddyMageplaza** [comment]
Hi @rommelfreddy,

Please accept my deepest apologies for the delay in response as I am facing some issues with paid extensions. 
On behalf of Mageplaza, I am thankful for your outstanding and significant contribution. However, we need to edit it much to make the Email Attachment module more flexible. Besides, code clean is required.  

Once again, thanks for spending your precious time here. Please allow me to close this pull request.
If you have any further questions/issues, please feel welcome to reach back out as we would be more than happy to assist.

Have a nice week!

**Comment by rommelfreddy** [comment]
Hello @TeddyMageplaza , 
so this PR will not be merged? 
Will this change be implemented in future releases, and when, in which version?

**Comment by TeddyMageplaza** [comment]
Hello @rommelfreddy,

About your question, your contribution is amazing but as I mentioned, we have to check carefully for each released version of all modules. Currently, we also have a lot of paid modules with a high priority need to update some functions, fix minor bugs... And EmailAttachments is not on that list. 

I can't estimate the time because it depends on our technical manager but of course, I have noted this feature in the **TO DO** list and we will check it as soon as possible.

Once again, thanks for spending your precious time here.
Have a nice day!

**Pull request closed without merging**
